### ISSUE TITLE
package gets all properties overwriten, besides the Model

### ISSUE THREAD

**Issue by opnoobkiller** [Roblox/roblox-blender-plugin#11]
How would I update something like a part's transparency? If I update something on a part publish it, and then update it in Blender, Blender changes completely overwrite the properties of a part, which means there should be something that links values together in the Add-On

**Comment by Nightriff** [comment]
Overwriting changes in studio is a limitation of the package ecosystem. The only connection between the Blender add-on and Roblox is through uploading new package versions, so it has no knowledge of Roblox-specific information, like instance properties.

Supporting preservation of changes to packages falls within scope of Packages on Roblox rather than the add-on. Roblox is acutely aware of this feature request and is working toward smoothing out package workflows.

I'm closing this as not planned for this add-on, since it's out of scope and the responsibility falls on Packages to support merging diffs.
