### ISSUE TITLE
Internal client error. No module named 'pyjwt_key_fetcher'

### ISSUE THREAD

**Issue by t3xellz** [Roblox/roblox-blender-plugin#14]
I get this message once i finish the last step of the login

**Comment by t3xellz** [comment]
![image](https://github.com/Roblox/roblox-blender-plugin/assets/143461992/d8e9ad05-ac4c-48bf-8d88-379f60e210b2)

**Comment by Nightriff** [comment]
That's odd, that dependency should have been installed during the dependency installation when the plugin first ran - it requires you to click "Install dependencies". Can you try uninstalling the plugin, re-installing it, and watching the terminal output during dependency installation to check for any errors?

**Comment by snakeboybenrich** [comment]
I get this message once i finish the last step of the login

**Comment by snakeboybenrich** [comment]
[
![Uploading 2.PNG…]()
](url)

**Comment by Nightriff** [comment]
@snakeboybenrich Your image did not upload properly

**Comment by pluh01** [comment]
I'm having the same

Internal client error
No module named 'pyjwt_key_fetcher'

I've done the Install dependencies procedure and reinstalled twice, but it keeps showing up.
Same as the first guy, the error pops up right after I click CONFIRM AND GIVE ACCESS

![image](https://github.com/Roblox/roblox-blender-plugin/assets/155758274/00671201-04c7-4142-a7fd-0b3fc13757bc)

Has any fix been made yet?

**Comment by Nightriff** [comment]
Thanks for adding your report to this issue. It seems you and a few others are experiencing this, but no exact cause has been identified yet,

@pluh01 Could you also please try the above step to get more info from the error, e.g. try uninstalling the plugin, re-installing it, and watch the terminal output during dependency installation to check for any errors?

To enable the terminal:
* On Windows, in Blender go to Window > Toggle System Console to see the console.
* On Mac OS, you'll need to start Blender from a terminal window.

**Comment by pluh01** [comment]
![image](https://github.com/Roblox/roblox-blender-plugin/assets/155758274/9f5ce83b-acb7-452f-93df-5c83340a8273)

My antivirus also gives me a warning when downloading dependencies, but I always unblock the file. Should I give it a try with my antivirus completely disabled?

**Comment by pluh01** [comment]
**SOLUTION FOUND**

While you are installing dependencies you have to completely disable your antivirus if you're encountering this issue, the antivirus blocks out the pyjwt-key-fetcher module during installation and it won't work even if you exclude it.

**Comment by Nightriff** [comment]
Thank you for sharing the output! To put any concerns at ease, `pyjwt-key-fetcher` is **not** malicious - it is a valid required dependency of the plugin that is supposed to be installed when the plugin first runs. If your antivirus is blocking it, it will cause this issue, and you need to **disable your antivirus during installation**, or otherwise prevent it from blocking this.

`pyjwt-key-fetcher` is used [here](https://github.com/Roblox/roblox-blender-plugin/blob/85baac63f2343a97065ed4dc35b53cbe82a15cc5/lib/request_login_details.py#L133C1-L134C48) to use the [kid](https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.4) property of the id token to look up the corresponding public key from Roblox's certificate endpoint, which is then used to verify that the id token was signed by Roblox. The `pyjwt-key-fetcher` library simplifies this fetching and key matching down to a simple single function call.
