### ISSUE TITLE
Can't log into plugin: Login request failed. 401 Authorization code may not be used from this device

### ISSUE THREAD

**Issue by devtaharbx** [Roblox/roblox-blender-plugin#41]
Error: Login request failed.
401, message='Authorization code may not be used from this device', url=URL('https://apis.roblox.com/oauth/v1/token')

I am getting this message after completing the account linking process. Please let me know how to fix this I have been trying for 2 days

**Comment by Nightriff** [comment]
Sorry you're having trouble logging in! This error can occur if your IP address changes during the login process.

I have experienced it when I tried to log in at an airport, for example, and was able to resolve it by switching to my phone's hotspot instead of using the public wifi. You may also try using (or turning off, if already using) a VPN.

If you would share, are there any unusual circumstances with your wifi connection? Collecting info on the types of practical situations where this error comes up may help diagnose the cause for anyone else experiencing the same problem.

**Comment by devtaharbx** [comment]
Wow i changed wifi to a different one and it worked but there is one thing. when I texture paint my object and upload, it doesnt update. I have auto update on. Only the change i make to the mesh are only uploaded but the texture is not loading. Do you know why?

**Comment by Nightriff** [comment]
Please open another issue for the texturing issues unrelated to logging in. Thanks!
