### ISSUE TITLE
Uploads from Blender to Roblox Studio are models instead of packages

### ISSUE THREAD

**Issue by Cvexreos** [Roblox/roblox-blender-plugin#43]
I am using Blender 4.0 and the latest version of the plugin. Whenever I upload anything from Blender to Roblox Studio they are models instead of packages.

**Comment by Nightriff** [comment]
@Cvexreos Would you please provide a screenshot or additional details about where you see it showing up as a model instead of a package?

I'm unable to reproduce this, this is what I see in Blender:
<img width="442" alt="image" src="https://github.com/Roblox/roblox-blender-plugin/assets/66378309/459017d7-71b4-4cb8-9bb4-59164bde7ae4">

And this is what I see in studio, under My Packages in my inventory tab of the Toolbox widget:
<img width="321" alt="image" src="https://github.com/Roblox/roblox-blender-plugin/assets/66378309/a743b87f-19b7-431e-935a-3a9eaf8cc582">

**Comment by Nightriff** [comment]
Closing this as not enough information is provided. Feel free to comment again if you have more information.
